import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'
import Header from "@/components/header";

const Dana = localFont({
  src: [
    {
      path: './assets/fonts/woff2/Dana-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './assets/fonts/woff2/Dana-Bold.woff2',
      weight: '700',
      style: 'bold',
    },
    {
      path: './assets/fonts/woff2/Dana-Black.woff2',
      weight: '900',
      style: 'bolder',
    },
    {
      path: './assets/fonts/woff2/Dana-Light.woff2',
      weight: '300',
      style: 'light',
    },
  ],
})

export const metadata: Metadata = {
  title: "Quick Commerce",
  description: "Generated by Basalam Quick Commerce tim",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Dana.className} py-10 md:px-10`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
